-- distribution
DROP TABLE IF EXISTS distribution;
CREATE TABLE distribution (
  id                        INT8 DEFAULT nextval('nsl_global_seq') NOT NULL,
  lock_version              INT8 DEFAULT 0                         NOT NULL,
  description               VARCHAR(100)                           NOT NULL,
  is_doubtfully_naturalised BOOLEAN DEFAULT FALSE                  NOT NULL,
  is_extinct                BOOLEAN DEFAULT FALSE                  NOT NULL,
  is_native                 BOOLEAN DEFAULT FALSE                  NOT NULL,
  is_naturalised            BOOLEAN DEFAULT FALSE                  NOT NULL,
  region                    VARCHAR(10)                            NOT NULL,
  sort_order                INT8                                   NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Qld', 100, false, false, true, false, 'Qld');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NSW', 200, false, false, true, false, 'NSW');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Vic', 300, false, false, true, false, 'Vic');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Tas', 400, false, false, true, false, 'Tas');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'SA', 500, false, false, true, false, 'SA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'WA', 600, false, false, true, false, 'WA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NT', 700, false, false, true, false, 'NT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ACT', 800, false, false, true, false, 'ACT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'LHI', 900, false, false, true, false, 'LHI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ChI', 1000, false, false, true, false, 'ChI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NI', 1100, false, false, true, false, 'NI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CoI', 1200, false, false, true, false, 'CoI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MI', 1300, false, false, true, false, 'MI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'AR', 1400, false, false, true, false, 'AR');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CSI', 1500, false, false, true, false, 'CSI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'HI', 1600, false, false, true, false, 'HI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MDI', 1700, false, false, true, false, 'MDI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CaI', 1800, false, false, true, false, 'CaI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Qld (naturalised)', 10100, false, false, false, true, 'Qld');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NSW (naturalised)', 10200, false, false, false, true, 'NSW');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Vic (naturalised)', 10300, false, false, false, true, 'Vic');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Tas (naturalised)', 10400, false, false, false, true, 'Tas');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'SA (naturalised)', 10500, false, false, false, true, 'SA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'WA (naturalised)', 10600, false, false, false, true, 'WA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NT (naturalised)', 10700, false, false, false, true, 'NT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ACT (naturalised)', 10800, false, false, false, true, 'ACT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'LHI (naturalised)', 10900, false, false, false, true, 'LHI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ChI (naturalised)', 101000, false, false, false, true, 'ChI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NI (naturalised)', 101100, false, false, false, true, 'NI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CoI (naturalised)', 101200, false, false, false, true, 'CoI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MI (naturalised)', 101300, false, false, false, true, 'MI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'AR (naturalised)', 101400, false, false, false, true, 'AR');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CSI (naturalised)', 101500, false, false, false, true, 'CSI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'HI (naturalised)', 101600, false, false, false, true, 'HI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MDI (naturalised)', 101700, false, false, false, true, 'MDI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CaI (naturalised)', 101800, false, false, false, true, 'CaI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Qld (doubtfully naturalised)', 20100, true, false, false, false, 'Qld');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NSW (doubtfully naturalised)', 20200, true, false, false, false, 'NSW');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Vic (doubtfully naturalised)', 20300, true, false, false, false, 'Vic');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Tas (doubtfully naturalised)', 20400, true, false, false, false, 'Tas');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'SA (doubtfully naturalised)', 20500, true, false, false, false, 'SA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'WA (doubtfully naturalised)', 20600, true, false, false, false, 'WA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NT (doubtfully naturalised)', 20700, true, false, false, false, 'NT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ACT (doubtfully naturalised)', 20800, true, false, false, false, 'ACT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'LHI (doubtfully naturalised)', 20900, true, false, false, false, 'LHI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ChI (doubtfully naturalised)', 201000, true, false, false, false, 'ChI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NI (doubtfully naturalised)', 201100, true, false, false, false, 'NI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CoI (doubtfully naturalised)', 201200, true, false, false, false, 'CoI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MI (doubtfully naturalised)', 201300, true, false, false, false, 'MI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'AR (doubtfully naturalised)', 201400, true, false, false, false, 'AR');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CSI (doubtfully naturalised)', 201500, true, false, false, false, 'CSI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'HI (doubtfully naturalised)', 201600, true, false, false, false, 'HI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MDI (doubtfully naturalised)', 201700, true, false, false, false, 'MDI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CaI (doubtfully naturalised)', 201800, true, false, false, false, 'CaI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Qld (native and naturalised)', 30100, false, false, true, true, 'Qld');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NSW (native and naturalised)', 30200, false, false, true, true, 'NSW');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Vic (native and naturalised)', 30300, false, false, true, true, 'Vic');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Tas (native and naturalised)', 30400, false, false, true, true, 'Tas');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'SA (native and naturalised)', 30500, false, false, true, true, 'SA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'WA (native and naturalised)', 30600, false, false, true, true, 'WA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NT (native and naturalised)', 30700, false, false, true, true, 'NT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ACT (native and naturalised)', 30800, false, false, true, true, 'ACT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'LHI (native and naturalised)', 30900, false, false, true, true, 'LHI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ChI (native and naturalised)', 301000, false, false, true, true, 'ChI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NI (native and naturalised)', 301100, false, false, true, true, 'NI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CoI (native and naturalised)', 301200, false, false, true, true, 'CoI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MI (native and naturalised)', 301300, false, false, true, true, 'MI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'AR (native and naturalised)', 301400, false, false, true, true, 'AR');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CSI (native and naturalised)', 301500, false, false, true, true, 'CSI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'HI (native and naturalised)', 301600, false, false, true, true, 'HI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MDI (native and naturalised)', 301700, false, false, true, true, 'MDI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CaI (native and naturalised)', 301800, false, false, true, true, 'CaI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Qld (extinct)', 40100, false, true, false, false, 'Qld');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NSW (extinct)', 40200, false, true, false, false, 'NSW');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Vic (extinct)', 40300, false, true, false, false, 'Vic');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'Tas (extinct)', 40400, false, true, false, false, 'Tas');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'SA (extinct)', 40500, false, true, false, false, 'SA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'WA (extinct)', 40600, false, true, false, false, 'WA');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NT (extinct)', 40700, false, true, false, false, 'NT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ACT (extinct)', 40800, false, true, false, false, 'ACT');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'LHI (extinct)', 40900, false, true, false, false, 'LHI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'ChI (extinct)', 401000, false, true, false, false, 'ChI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'NI (extinct)', 401100, false, true, false, false, 'NI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CoI (extinct)', 401200, false, true, false, false, 'CoI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MI (extinct)', 401300, false, true, false, false, 'MI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'AR (extinct)', 401400, false, true, false, false, 'AR');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CSI (extinct)', 401500, false, true, false, false, 'CSI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'HI (extinct)', 401600, false, true, false, false, 'HI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'MDI (extinct)', 401700, false, true, false, false, 'MDI');
INSERT INTO public.distribution (id, lock_version, description, sort_order, is_doubtfully_naturalised, is_extinct, is_native, is_naturalised, region) VALUES (nextval('nsl_global_seq'), 0, 'CaI (extinct)', 401800, false, true, false, false, 'CaI');

UPDATE db_version SET version = 26 WHERE id = 1;
